import Foundation
import Observation

// ── 16 dil lokalizasyon ───────────────────────────────────────────────────────
// L10n.shared.lang değişince @Observable sayesinde tüm View'lar yenilenir.
// t("key") global fonksiyonu ile kullanılır.
@MainActor
@Observable
final class L10n {
    static let shared = L10n()
    static let languages = ["tr","en","es","fr","de","it","pt","ru","ar","zh","ja","ko","az","uk","fa","hi"]
    static let names: [String:String] = [
        "tr":"Türkçe","en":"English","es":"Español","fr":"Français","de":"Deutsch","it":"Italiano",
        "pt":"Português","ru":"Русский","ar":"العربية","zh":"中文","ja":"日本語","ko":"한국어",
        "az":"Azərbaycan","uk":"Українська","fa":"فارسی","hi":"हिन्दी"
    ]

    var lang: String {
        didSet { UserDefaults.standard.set(lang, forKey: "lang") }
    }

    init() {
        let saved = UserDefaults.standard.string(forKey: "lang")
        let sys = Locale.current.language.languageCode?.identifier ?? "en"
        if let saved, Self.languages.contains(saved) { lang = saved }
        else if Self.languages.contains(sys)         { lang = sys }
        else                                          { lang = "en" }
    }

    func t(_ key: String) -> String {
        Self.dict[key]?[lang] ?? Self.dict[key]?["en"] ?? key
    }

    static let dict: [String:[String:String]] = [
        "tab_map":       ["tr":"Harita","en":"Map","es":"Mapa","fr":"Carte","de":"Karte","it":"Mappa","pt":"Mapa","ru":"Карта","ar":"خريطة","zh":"地图","ja":"地図","ko":"지도","az":"Xəritə","uk":"Карта","fa":"نقشه","hi":"मानचित्र"],
        "tab_market":    ["tr":"Piyasa","en":"Market","es":"Mercado","fr":"Marché","de":"Markt","it":"Mercato","pt":"Mercado","ru":"Рынок","ar":"السوق","zh":"市场","ja":"市場","ko":"시장","az":"Bazar","uk":"Ринок","fa":"بازار","hi":"बाज़ार"],
        "tab_portfolio": ["tr":"Portföy","en":"Portfolio","es":"Cartera","fr":"Portefeuille","de":"Portfolio","it":"Portafoglio","pt":"Carteira","ru":"Портфель","ar":"المحفظة","zh":"投资组合","ja":"ポート","ko":"포트폴리오","az":"Portfel","uk":"Портфель","fa":"سبد","hi":"पोर्टफोलियो"],
        "tab_store":     ["tr":"Mağaza","en":"Store","es":"Tienda","fr":"Boutique","de":"Shop","it":"Negozio","pt":"Loja","ru":"Магазин","ar":"المتجر","zh":"商店","ja":"ストア","ko":"상점","az":"Mağaza","uk":"Магазин","fa":"فروشگاه","hi":"स्टोर"],
        "tab_rankings":  ["tr":"Sıralama","en":"Ranks","es":"Ranking","fr":"Classement","de":"Rang","it":"Classifica","pt":"Ranking","ru":"Рейтинг","ar":"الترتيب","zh":"排名","ja":"順位","ko":"순위","az":"Reytinq","uk":"Рейтинг","fa":"رتبه","hi":"रैंक"],
        "tab_settings":  ["tr":"Ayarlar","en":"Settings","es":"Ajustes","fr":"Réglages","de":"Einstellungen","it":"Impostazioni","pt":"Ajustes","ru":"Настройки","ar":"الإعدادات","zh":"设置","ja":"設定","ko":"설정","az":"Tənzimləmələr","uk":"Налаштування","fa":"تنظیمات","hi":"सेटिंग्स"],
        "tab_forex":     ["tr":"Döviz","en":"Forex","es":"Divisas","fr":"Devises","de":"Devisen","it":"Valute","pt":"Câmbio","ru":"Форекс","ar":"عملات","zh":"外汇","ja":"為替","ko":"환전","az":"Valyuta","uk":"Форекс","fa":"ارز","hi":"फॉरेक्स"],
        "market_index":  ["tr":"Piyasa Endeksi","en":"Market Index","es":"Índice","fr":"Indice","de":"Marktindex","it":"Indice","pt":"Índice","ru":"Индекс","ar":"المؤشر","zh":"市场指数","ja":"市場指数","ko":"시장 지수","az":"İndeks","uk":"Індекс","fa":"شاخص","hi":"सूचकांक"],
        "sell":          ["tr":"Sat","en":"Sell","es":"Vender","fr":"Vendre","de":"Verkaufen","it":"Vendi","pt":"Vender","ru":"Продать","ar":"بيع","zh":"卖出","ja":"売却","ko":"판매","az":"Sat","uk":"Продати","fa":"فروش","hi":"बेचें"],
        "sold":          ["tr":"satıldı","en":"sold","es":"vendido","fr":"vendu","de":"verkauft","it":"venduto","pt":"vendido","ru":"продано","ar":"بيع","zh":"已售","ja":"売却","ko":"판매됨","az":"satıldı","uk":"продано","fa":"فروخته","hi":"बिका"],
        "cash":          ["tr":"NAKİT","en":"CASH","es":"EFECTIVO","fr":"CASH","de":"BARGELD","it":"CONTANTI","pt":"DINHEIRO","ru":"НАЛИЧНЫЕ","ar":"نقد","zh":"现金","ja":"現金","ko":"현금","az":"NAĞD","uk":"ГОТІВКА","fa":"نقد","hi":"नकद"],
        "investor":      ["tr":"Yatırımcı","en":"Investor","es":"Inversor","fr":"Investisseur","de":"Investor","it":"Investitore","pt":"Investidor","ru":"Инвестор","ar":"مستثمر","zh":"投资者","ja":"投資家","ko":"투자자","az":"İnvestor","uk":"Інвестор","fa":"سرمایه‌گذار","hi":"निवेशक"],
        "buy":           ["tr":"Satın Al","en":"Buy","es":"Comprar","fr":"Acheter","de":"Kaufen","it":"Compra","pt":"Comprar","ru":"Купить","ar":"شراء","zh":"购买","ja":"購入","ko":"구매","az":"Al","uk":"Купити","fa":"خرید","hi":"खरीदें"],
        "cancel":        ["tr":"İptal","en":"Cancel","es":"Cancelar","fr":"Annuler","de":"Abbrechen","it":"Annulla","pt":"Cancelar","ru":"Отмена","ar":"إلغاء","zh":"取消","ja":"キャンセル","ko":"취소","az":"Ləğv","uk":"Скасувати","fa":"لغو","hi":"रद्द"],
        "insufficient":  ["tr":"Yetersiz","en":"Low funds","es":"Sin fondos","fr":"Fonds bas","de":"Zu wenig","it":"Fondi bassi","pt":"Sem fundos","ru":"Мало средств","ar":"رصيد قليل","zh":"余额不足","ja":"残高不足","ko":"잔액 부족","az":"Kifayət deyil","uk":"Мало коштів","fa":"موجودی کم","hi":"अपर्याप्त"],
        "owned":         ["tr":"Sahipsiniz","en":"Owned","es":"En propiedad","fr":"Possédé","de":"Im Besitz","it":"Posseduto","pt":"Possuído","ru":"В собственности","ar":"مملوك","zh":"已拥有","ja":"所有済み","ko":"보유 중","az":"Sizindir","uk":"У власності","fa":"مالک","hi":"स्वामित्व"],
        "search_ph":     ["tr":"Mülk, şehir ara…","en":"Search property, city…","es":"Buscar propiedad, ciudad…","fr":"Bien, ville…","de":"Immobilie, Stadt…","it":"Proprietà, città…","pt":"Imóvel, cidade…","ru":"Объект, город…","ar":"عقار، مدينة…","zh":"搜索房产、城市…","ja":"物件・都市…","ko":"매물, 도시…","az":"Əmlak, şəhər…","uk":"Об'єкт, місто…","fa":"ملک، شهر…","hi":"संपत्ति, शहर…"],
        "net_worth":     ["tr":"Net Değer","en":"Net Worth","es":"Patrimonio","fr":"Valeur nette","de":"Nettowert","it":"Patrimonio","pt":"Patrimônio","ru":"Капитал","ar":"صافي الثروة","zh":"净资产","ja":"純資産","ko":"순자산","az":"Xalis dəyər","uk":"Капітал","fa":"ارزش خالص","hi":"कुल संपत्ति"],
        "daily_income":  ["tr":"Günlük Gelir","en":"Daily Income","es":"Ingreso diario","fr":"Revenu/jour","de":"Tageseinkommen","it":"Reddito/giorno","pt":"Renda diária","ru":"Доход/день","ar":"دخل يومي","zh":"日收入","ja":"日収","ko":"일일 수입","az":"Günlük gəlir","uk":"Дохід/день","fa":"درآمد روزانه","hi":"दैनिक आय"],
        "property_count":["tr":"Mülk Sayısı","en":"Properties","es":"Propiedades","fr":"Biens","de":"Immobilien","it":"Proprietà","pt":"Imóveis","ru":"Объекты","ar":"العقارات","zh":"房产数","ja":"物件数","ko":"매물 수","az":"Əmlak sayı","uk":"Об'єкти","fa":"تعداد املاک","hi":"संपत्तियाँ"],
        "no_props":      ["tr":"Henüz mülkün yok","en":"No properties yet","es":"Aún sin propiedades","fr":"Aucun bien","de":"Noch keine Immobilien","it":"Nessuna proprietà","pt":"Nenhum imóvel","ru":"Пока нет объектов","ar":"لا عقارات بعد","zh":"还没有房产","ja":"物件なし","ko":"보유 매물 없음","az":"Hələ əmlak yoxdur","uk":"Поки немає об'єктів","fa":"هنوز ملکی ندارید","hi":"अभी कोई संपत्ति नहीं"],
        "area_props":    ["tr":"Bu bölgedeki mülkler","en":"Properties here","es":"Propiedades aquí","fr":"Biens ici","de":"Immobilien hier","it":"Proprietà qui","pt":"Imóveis aqui","ru":"Объекты здесь","ar":"عقارات هنا","zh":"此处房产","ja":"このエリアの物件","ko":"이 지역 매물","az":"Buradakı əmlaklar","uk":"Об'єкти тут","fa":"املاک اینجا","hi":"यहाँ की संपत्तियाँ"],
        "cash_packs":    ["tr":"Nakit Paketleri","en":"Cash Packs","es":"Paquetes de efectivo","fr":"Packs de cash","de":"Bargeldpakete","it":"Pacchetti contanti","pt":"Pacotes de dinheiro","ru":"Пакеты наличных","ar":"حزم نقدية","zh":"现金包","ja":"現金パック","ko":"현금 팩","az":"Nağd paketləri","uk":"Пакети готівки","fa":"بسته‌های نقدی","hi":"नकद पैक"],
        "live_board":    ["tr":"Canlı liderlik","en":"Live leaderboard","es":"Clasificación en vivo","fr":"Classement live","de":"Live-Rangliste","it":"Classifica live","pt":"Ranking ao vivo","ru":"Живой рейтинг","ar":"الترتيب المباشر","zh":"实时排行","ja":"ライブ順位","ko":"실시간 순위","az":"Canlı reytinq","uk":"Живий рейтинг","fa":"جدول زنده","hi":"लाइव रैंकिंग"],
        "reset_game":    ["tr":"Oyunu sıfırla","en":"Reset game","es":"Reiniciar","fr":"Réinitialiser","de":"Spiel zurücksetzen","it":"Reset","pt":"Reiniciar","ru":"Сбросить игру","ar":"إعادة تعيين","zh":"重置游戏","ja":"リセット","ko":"게임 초기화","az":"Sıfırla","uk":"Скинути","fa":"بازنشانی","hi":"रीसेट"],
        "language":      ["tr":"Dil","en":"Language","es":"Idioma","fr":"Langue","de":"Sprache","it":"Lingua","pt":"Idioma","ru":"Язык","ar":"اللغة","zh":"语言","ja":"言語","ko":"언어","az":"Dil","uk":"Мова","fa":"زبان","hi":"भाषा"],
        "confirm":       ["tr":"Onayla","en":"Confirm","es":"Confirmar","fr":"Confirmer","de":"Bestätigen","it":"Conferma","pt":"Confirmar","ru":"Подтвердить","ar":"تأكيد","zh":"确认","ja":"確認","ko":"확인","az":"Təsdiqlə","uk":"Підтвердити","fa":"تأیید","hi":"पुष्टि"],
        "owned_msg":     ["tr":"Bu mülk senin","en":"You own this","es":"Es tuyo","fr":"Vous le possédez","de":"Gehört dir","it":"È tuo","pt":"É seu","ru":"Это ваше","ar":"هذا ملكك","zh":"已归你所有","ja":"所有済み","ko":"보유 중","az":"Sizindir","uk":"Це ваше","fa":"مال شماست","hi":"यह आपका है"],
        "low_funds":     ["tr":"Yetersiz bakiye","en":"Insufficient funds","es":"Fondos insuficientes","fr":"Fonds insuffisants","de":"Unzureichendes Guthaben","it":"Fondi insufficienti","pt":"Saldo insuficiente","ru":"Недостаточно средств","ar":"رصيد غير كافٍ","zh":"余额不足","ja":"残高不足","ko":"잔액 부족","az":"Balans kifayət etmir","uk":"Недостатньо коштів","fa":"موجودی ناکافی","hi":"अपर्याप्त शेष"],
        "price":         ["tr":"Fiyat","en":"Price","es":"Precio","fr":"Prix","de":"Preis","it":"Prezzo","pt":"Preço","ru":"Цена","ar":"السعر","zh":"价格","ja":"価格","ko":"가격","az":"Qiymət","uk":"Ціна","fa":"قیمت","hi":"मूल्य"],
        "income_day":    ["tr":"Gelir/gün","en":"Income/day","es":"Ingreso/día","fr":"Revenu/jour","de":"Einkommen/Tag","it":"Reddito/giorno","pt":"Renda/dia","ru":"Доход/день","ar":"دخل/يوم","zh":"收入/天","ja":"収入/日","ko":"수입/일","az":"Gəlir/gün","uk":"Дохід/день","fa":"درآمد/روز","hi":"आय/दिन"],
        "loading":       ["tr":"Yükleniyor…","en":"Loading…"],
        "map_downloading":  ["tr":"Harita indiriliyor","en":"Downloading map","es":"Descargando mapa","fr":"Téléchargement de la carte","de":"Karte wird geladen","it":"Download mappa","pt":"Baixando mapa","ru":"Загрузка карты","ar":"جارٍ تنزيل الخريطة","zh":"正在下载地图","ja":"マップをダウンロード中","ko":"지도 다운로드 중","az":"Xəritə yüklənir","uk":"Завантаження карти","fa":"در حال دانلود نقشه","hi":"मानचित्र डाउनलोड हो रहा है"],
        "city_downloading": ["tr":"Şehir mülkleri iniyor","en":"Loading city properties","es":"Cargando propiedades","fr":"Chargement des propriétés","de":"Lade Immobilien","it":"Caricamento proprietà","pt":"Carregando imóveis","ru":"Загрузка объектов","ar":"جارٍ تحميل العقارات","zh":"正在加载房产","ja":"物件を読み込み中","ko":"부동산 불러오는 중","az":"Şəhər mülkləri yüklənir","uk":"Завантаження об'єктів","fa":"در حال بارگیری املاک","hi":"संपत्तियाँ लोड हो रही हैं"],
        "list":          ["tr":"Liste","en":"List","es":"Lista","fr":"Liste","de":"Liste","it":"Lista","pt":"Lista","ru":"Список","ar":"قائمة","zh":"列表","ja":"リスト","ko":"목록","az":"Siyahı","uk":"Список","fa":"فهرست","hi":"सूची"],
        "owner":         ["tr":"Sahibi","en":"Owner","es":"Dueño","fr":"Propriétaire","de":"Eigentümer","it":"Proprietario","pt":"Dono","ru":"Владелец","ar":"المالك","zh":"业主","ja":"所有者","ko":"소유자","az":"Sahibi","uk":"Власник","fa":"مالک","hi":"मालिक"],
        "you":           ["tr":"Sen","en":"You","es":"Tú","fr":"Vous","de":"Du","it":"Tu","pt":"Você","ru":"Вы","ar":"أنت","zh":"你","ja":"あなた","ko":"나","az":"Sən","uk":"Ви","fa":"شما","hi":"आप"],
        "available":     ["tr":"Sahipsiz — satın alınabilir","en":"Unowned — available","es":"Disponible","fr":"Disponible","de":"Verfügbar","it":"Disponibile","pt":"Disponível","ru":"Свободно","ar":"متاح","zh":"可购买","ja":"購入可","ko":"구매 가능","az":"Boşdur","uk":"Вільно","fa":"در دسترس","hi":"उपलब्ध"],
        "send_offer":    ["tr":"Teklif Yolla","en":"Send Offer","es":"Enviar oferta","fr":"Faire une offre","de":"Angebot senden","it":"Invia offerta","pt":"Enviar oferta","ru":"Сделать предложение","ar":"إرسال عرض","zh":"出价","ja":"オファー","ko":"제안하기","az":"Təklif göndər","uk":"Запропонувати","fa":"پیشنهاد","hi":"प्रस्ताव भेजें"],
        "offer":         ["tr":"Teklif","en":"Offer","es":"Oferta","fr":"Offre","de":"Angebot","it":"Offerta","pt":"Oferta","ru":"Оферта","ar":"عرض","zh":"出价","ja":"オファー","ko":"제안","az":"Təklif","uk":"Оферта","fa":"پیشنهاد","hi":"प्रस्ताव"],
        "offer_accepted":["tr":"Teklif kabul edildi! Mülk senin.","en":"Offer accepted! It's yours."],
        "offer_rejected":["tr":"Teklif reddedildi — daha yüksek dene.","en":"Offer rejected — try higher."],
        "search_place":  ["tr":"Yer ara: şehir, ülke, semt…","en":"Search place: city, country…","es":"Buscar lugar…","fr":"Chercher un lieu…","de":"Ort suchen…","it":"Cerca luogo…","pt":"Buscar local…","ru":"Поиск места…","ar":"ابحث عن مكان…","zh":"搜索地点…","ja":"場所を検索…","ko":"장소 검색…","az":"Yer axtar…","uk":"Пошук місця…","fa":"جستجوی مکان…","hi":"स्थान खोजें…"],
        "retry":         ["tr":"Tekrar dene","en":"Retry","es":"Reintentar","fr":"Réessayer","de":"Erneut versuchen","it":"Riprova","pt":"Tentar de novo","ru":"Повторить","ar":"إعادة المحاولة","zh":"重试","ja":"再試行","ko":"다시 시도","az":"Yenidən","uk":"Повторити","fa":"تلاش مجدد","hi":"पुनः प्रयास"],
        "auth_checking": ["tr":"Kimlik doğrulanıyor…","en":"Verifying identity…","es":"Verificando identidad…","fr":"Vérification…","de":"Identität wird geprüft…","it":"Verifica identità…","pt":"Verificando…","ru":"Проверка…","ar":"جارٍ التحقق…","zh":"正在验证…","ja":"確認中…","ko":"확인 중…","az":"Yoxlanılır…","uk":"Перевірка…","fa":"در حال تأیید…","hi":"पहचान जाँच…"],
        "auth_required": ["tr":"Bağlantı ve kimlik gerekli","en":"Connection & identity required","es":"Se requiere conexión","fr":"Connexion requise","de":"Verbindung erforderlich","it":"Connessione richiesta","pt":"Conexão necessária","ru":"Требуется подключение","ar":"يلزم الاتصال والهوية","zh":"需要连接与身份","ja":"接続と認証が必要","ko":"연결과 인증 필요","az":"Bağlantı lazımdır","uk":"Потрібне з'єднання","fa":"اتصال لازم است","hi":"कनेक्शन आवश्यक"],
        "auth_online_note":["tr":"Hooder çevrimiçi oynanır. Devam etmek için internet bağlantısı gerekir.","en":"Hooder is played online. An internet connection is required to continue.","es":"Hooder se juega en línea. Se requiere internet.","fr":"Hooder se joue en ligne. Internet requis.","de":"Hooder wird online gespielt. Internet erforderlich.","it":"Hooder si gioca online. Serve internet.","pt":"Hooder é jogado online. Internet necessária.","ru":"Hooder играется онлайн. Нужен интернет.","ar":"تُلعب Hooder عبر الإنترنت. يلزم اتصال بالإنترنت.","zh":"Hooder 为在线游戏，需要联网。","ja":"Hooderはオンライン専用です。接続が必要です。","ko":"Hooder는 온라인 전용입니다. 인터넷이 필요합니다.","az":"Hooder onlayn oynanır. İnternet lazımdır.","uk":"Hooder грається онлайн. Потрібен інтернет.","fa":"Hooder آنلاین است. اینترنت لازم است.","hi":"Hooder ऑनलाइन है। इंटरनेट आवश्यक है।"],
        "vip_title":     ["tr":"VIP Üyelik","en":"VIP Membership"],
        "vip_active":    ["tr":"✓ Aktif","en":"✓ Active"],
        "vip_perk_income":   ["tr":"+%25 günlük gelir","en":"+25% daily income"],
        "vip_perk_badge":    ["tr":"VIP rozeti + altın tema","en":"VIP badge + gold theme"],
        "vip_perk_exclusive":["tr":"Özel & erken mülkler","en":"Exclusive & early properties"],
        "sub_disclosure":["tr":"Hooder VIP otomatik yenilenen bir aboneliktir. Ücret satın alma onayında Apple Kimliğine yansır; dönem bitiminden en az 24 saat önce iptal edilmezse otomatik yenilenir. Ayarlar → Apple Kimliği → Abonelikler'den istediğin zaman yönet/iptal et.","en":"Hooder VIP is an auto-renewable subscription. Payment is charged to your Apple ID at confirmation; it renews automatically unless canceled at least 24 hours before the period ends. Manage or cancel anytime in Settings → Apple ID → Subscriptions."],
        "privacy":["tr":"Gizlilik Politikası","en":"Privacy Policy","es":"Privacidad","fr":"Confidentialité","de":"Datenschutz","it":"Privacy","pt":"Privacidade","ru":"Конфиденциальность","ar":"الخصوصية","zh":"隐私政策","ja":"プライバシー","ko":"개인정보","az":"Məxfilik","uk":"Конфіденційність","fa":"حریم خصوصی","hi":"गोपनीयता"],
        "terms":["tr":"Kullanım Şartları","en":"Terms of Use","es":"Términos","fr":"Conditions","de":"Nutzungsbedingungen","it":"Termini","pt":"Termos","ru":"Условия","ar":"الشروط","zh":"使用条款","ja":"利用規約","ko":"이용약관","az":"İstifadə şərtləri","uk":"Умови","fa":"شرایط","hi":"शर्तें"],

        // ── Onboarding (ilk açılış karşılaması) ──
        "ob_skip":         ["tr":"Atla","en":"Skip","es":"Saltar","fr":"Passer","de":"Überspringen","it":"Salta","pt":"Pular","ru":"Пропустить","ar":"تخطّي","zh":"跳过","ja":"スキップ","ko":"건너뛰기","az":"Keç","uk":"Пропустити","fa":"رد کردن","hi":"छोड़ें"],
        "ob_next":         ["tr":"İleri","en":"Next","es":"Siguiente","fr":"Suivant","de":"Weiter","it":"Avanti","pt":"Avançar","ru":"Далее","ar":"التالي","zh":"下一步","ja":"次へ","ko":"다음","az":"İrəli","uk":"Далі","fa":"بعدی","hi":"आगे"],
        "ob_start":        ["tr":"Oynamaya başla","en":"Start playing","es":"Empezar a jugar","fr":"Commencer à jouer","de":"Jetzt spielen","it":"Inizia a giocare","pt":"Começar a jogar","ru":"Начать игру","ar":"ابدأ اللعب","zh":"开始游戏","ja":"プレイを始める","ko":"게임 시작","az":"Oynamağa başla","uk":"Почати гру","fa":"شروع بازی","hi":"खेलना शुरू करें"],
        "ob_notify_later": ["tr":"Şimdi değil","en":"Not now","es":"Ahora no","fr":"Pas maintenant","de":"Nicht jetzt","it":"Non ora","pt":"Agora não","ru":"Не сейчас","ar":"ليس الآن","zh":"暂不","ja":"あとで","ko":"나중에","az":"İndi yox","uk":"Не зараз","fa":"الان نه","hi":"अभी नहीं"],
        "ob_1_title": ["tr":"Gerçek dünyayı ele geçir","en":"Own the real world","es":"Conquista el mundo real","fr":"Possède le monde réel","de":"Beherrsche die echte Welt","it":"Conquista il mondo reale","pt":"Domine o mundo real","ru":"Завладей реальным миром","ar":"امتلك العالم الحقيقي","zh":"掌控真实世界","ja":"現実世界を手に入れよう","ko":"현실 세계를 손에 넣으세요","az":"Real dünyanı ələ keçir","uk":"Заволодій реальним світом","fa":"دنیای واقعی را تصاحب کن","hi":"असली दुनिया पर कब्ज़ा करें"],
        "ob_1_body":  ["tr":"Canlı uydu haritasında gerçek binaları, gerçek konumlarında satın al.","en":"Buy real buildings at their true locations on a live satellite map.","es":"Compra edificios reales en sus ubicaciones reales sobre un mapa satelital en vivo.","fr":"Achète de vrais bâtiments à leur emplacement réel sur une carte satellite en direct.","de":"Kaufe echte Gebäude an ihren realen Standorten auf einer Live-Satellitenkarte.","it":"Compra edifici reali nelle loro vere posizioni su una mappa satellitare dal vivo.","pt":"Compre prédios reais em suas localizações reais em um mapa de satélite ao vivo.","ru":"Покупай настоящие здания в их реальных местах на живой спутниковой карте.","ar":"اشترِ مبانيَ حقيقية في مواقعها الفعلية على خريطة أقمار صناعية حيّة.","zh":"在实时卫星地图上，于真实位置购买真实建筑。","ja":"ライブ衛星マップ上で、実在する建物を本当の場所で購入しよう。","ko":"실시간 위성 지도에서 실제 위치의 진짜 건물을 사세요.","az":"Canlı peyk xəritəsində real binaları öz real yerlərində al.","uk":"Купуй справжні будівлі в їхніх реальних місцях на живій супутниковій карті.","fa":"روی نقشه ماهواره‌ای زنده، ساختمان‌های واقعی را در مکان واقعی‌شان بخر.","hi":"लाइव सैटेलाइट मैप पर असली इमारतें उनकी असली जगहों पर खरीदें।"],
        "ob_2_title": ["tr":"Tek canlı ekonomi","en":"One living economy","es":"Una economía viva","fr":"Une économie vivante","de":"Eine lebendige Wirtschaft","it":"Un'unica economia viva","pt":"Uma economia viva","ru":"Единая живая экономика","ar":"اقتصاد حيّ واحد","zh":"唯一的活经济","ja":"ひとつの生きた経済","ko":"살아 있는 하나의 경제","az":"Tək canlı iqtisadiyyat","uk":"Єдина жива економіка","fa":"یک اقتصاد زنده","hi":"एक जीवंत अर्थव्यवस्था"],
        "ob_2_body":  ["tr":"Herkes tek paylaşımlı piyasada işlem yapar — dünya alıp sattıkça fiyatlar oynar.","en":"Every player trades in one shared market — prices move as the world buys and sells.","es":"Todos operan en un único mercado compartido: los precios se mueven mientras el mundo compra y vende.","fr":"Tous les joueurs échangent sur un seul marché partagé — les prix bougent au gré des achats et des ventes.","de":"Alle handeln in einem gemeinsamen Markt – die Preise bewegen sich, wenn die Welt kauft und verkauft.","it":"Tutti i giocatori operano in un unico mercato condiviso: i prezzi si muovono mentre il mondo compra e vende.","pt":"Todos negociam em um único mercado compartilhado — os preços mudam à medida que o mundo compra e vende.","ru":"Все игроки торгуют на одном общем рынке — цены меняются, пока мир покупает и продаёт.","ar":"يتداول كل اللاعبين في سوق واحدة مشتركة — تتحرّك الأسعار مع بيع العالم وشرائه.","zh":"所有玩家在同一个共享市场交易——世界买卖之间，价格随之波动。","ja":"すべてのプレイヤーが一つの共有市場で取引——世界が売買するたびに価格が動く。","ko":"모든 플레이어가 하나의 공유 시장에서 거래합니다 — 세계가 사고팔 때마다 가격이 움직입니다.","az":"Hər oyunçu tək paylaşılan bazarda ticarət edir — dünya alıb-satdıqca qiymətlər dəyişir.","uk":"Усі гравці торгують на одному спільному ринку — ціни рухаються, поки світ купує й продає.","fa":"همه بازیکنان در یک بازار مشترک معامله می‌کنند — با خرید و فروش دنیا، قیمت‌ها تغییر می‌کنند.","hi":"हर खिलाड़ी एक ही साझा बाज़ार में व्यापार करता है — दुनिया के खरीदने-बेचने के साथ कीमतें बदलती हैं।"],
        "ob_3_title": ["tr":"15 milyon $ ile başla","en":"Start with $15M","es":"Empieza con 15 M$","fr":"Commence avec 15 M$","de":"Starte mit 15 Mio. $","it":"Inizia con 15 M$","pt":"Comece com US$ 15 mi","ru":"Начни с $15 млн","ar":"ابدأ بـ 15 مليون دولار","zh":"以 1500 万美元起步","ja":"1500万ドルからスタート","ko":"1,500만 달러로 시작","az":"15 milyon $ ilə başla","uk":"Почни з $15 млн","fa":"با ۱۵ میلیون دلار شروع کن","hi":"$1.5 करोड़ से शुरू करें"],
        "ob_3_body":  ["tr":"İlk mülkünü kap, döviz al-sat, rakipleri geç ve imparatorluğunu kur.","en":"Grab your first property, trade forex, outbid rivals and build your empire.","es":"Consigue tu primera propiedad, opera con divisas, supera a tus rivales y construye tu imperio.","fr":"Attrape ta première propriété, échange des devises, surenchéris sur tes rivaux et bâtis ton empire.","de":"Schnapp dir deine erste Immobilie, handle mit Devisen, überbiete Rivalen und baue dein Imperium.","it":"Afferra la tua prima proprietà, fai trading di valute, batti i rivali e costruisci il tuo impero.","pt":"Garanta seu primeiro imóvel, negocie moedas, supere os rivais e construa seu império.","ru":"Захвати первую недвижимость, торгуй валютой, обходи соперников и строй свою империю.","ar":"احصل على عقارك الأول، تاجر بالعملات، تفوّق على منافسيك وابنِ إمبراطوريتك.","zh":"抢下你的第一处房产，交易外汇，击败对手，打造你的帝国。","ja":"最初の物件を手に入れ、為替を取引し、ライバルを出し抜いて帝国を築こう。","ko":"첫 부동산을 차지하고, 외환을 거래하고, 라이벌을 제치고 제국을 세우세요.","az":"İlk mülkünü tut, valyuta al-sat, rəqibləri keç və imperiyanı qur.","uk":"Захопи першу нерухомість, торгуй валютою, обійди суперників і збудуй свою імперію.","fa":"اولین ملکت را بگیر، ارز معامله کن، از رقبا پیشی بگیر و امپراتوری‌ات را بساز.","hi":"अपनी पहली संपत्ति हथियाएं, विदेशी मुद्रा का व्यापार करें, प्रतिद्वंद्वियों को पछाड़ें और अपना साम्राज्य बनाएं।"],
        "ob_4_title": ["tr":"Fırsatları kaçırma","en":"Never miss a deal","es":"No te pierdas ninguna oportunidad","fr":"Ne rate aucune bonne affaire","de":"Verpasse keinen Deal","it":"Non perdere nessun affare","pt":"Nunca perca uma oportunidade","ru":"Не упусти ни одной сделки","ar":"لا تفوّت أي صفقة","zh":"绝不错过好机会","ja":"チャンスを逃さない","ko":"기회를 놓치지 마세요","az":"Fürsətləri qaçırma","uk":"Не пропусти жодної угоди","fa":"هیچ فرصتی را از دست نده","hi":"कोई मौका न चूकें"],
        "ob_4_body":  ["tr":"Kiran biriktiğinde ya da bir rakip mülküne göz diktiğinde haberin olsun.","en":"Get a nudge when your income piles up or a rival moves on your turf.","es":"Recibe un aviso cuando tus ingresos se acumulen o un rival vaya por tu territorio.","fr":"Reçois une alerte quand tes revenus s'accumulent ou qu'un rival lorgne ton territoire.","de":"Erhalte einen Hinweis, wenn sich deine Einnahmen häufen oder ein Rivale dein Gebiet ins Visier nimmt.","it":"Ricevi una notifica quando i tuoi incassi si accumulano o un rivale punta il tuo territorio.","pt":"Receba um aviso quando sua renda acumular ou um rival avançar sobre seu território.","ru":"Получай сигнал, когда доход накапливается или соперник посягает на твою территорию.","ar":"احصل على تنبيه عندما يتراكم دخلك أو يطمع منافس في منطقتك.","zh":"当收入堆积或对手觊觎你的地盘时，及时获得提醒。","ja":"収入がたまったり、ライバルが縄張りを狙ったりしたら通知が届く。","ko":"수입이 쌓이거나 라이벌이 당신의 영역을 노릴 때 알림을 받으세요.","az":"Gəlirin yığılanda və ya rəqib ərazinə göz dikəndə xəbərin olsun.","uk":"Отримуй сповіщення, коли дохід накопичується або суперник зазіхає на твою територію.","fa":"وقتی درآمدت انباشته شد یا رقیبی به قلمروت چشم دوخت، خبردار شو.","hi":"जब आपकी आय जमा हो जाए या कोई प्रतिद्वंद्वी आपके इलाके पर नज़र डाले, तो सूचना पाएं।"],

        // ── Yerel retention bildirimleri ──
        "notif_d1_title": ["tr":"💰 Kiran birikiyor","en":"💰 Your rent is piling up","es":"💰 Tu renta se acumula","fr":"💰 Tes loyers s'accumulent","de":"💰 Deine Mieten häufen sich","it":"💰 I tuoi affitti si accumulano","pt":"💰 Seu aluguel está acumulando","ru":"💰 Твоя рента копится","ar":"💰 إيجارك يتراكم","zh":"💰 你的租金在累积","ja":"💰 家賃がたまっています","ko":"💰 임대 수입이 쌓이고 있어요","az":"💰 Kiran yığılır","uk":"💰 Твоя рента накопичується","fa":"💰 اجاره‌ات در حال انباشته‌شدن است","hi":"💰 आपका किराया जमा हो रहा है"],
        "notif_d1_body":  ["tr":"Sen yokken mülklerin kazandı. Gel topla!","en":"Your properties earned while you were away. Come collect!","es":"Tus propiedades ganaron mientras no estabas. ¡Ven a cobrar!","fr":"Tes propriétés ont rapporté en ton absence. Viens encaisser !","de":"Deine Immobilien haben verdient, während du weg warst. Hol dir dein Geld!","it":"Le tue proprietà hanno guadagnato mentre eri via. Vieni a incassare!","pt":"Seus imóveis renderam enquanto você esteve fora. Venha recolher!","ru":"Пока тебя не было, недвижимость приносила доход. Забери его!","ar":"ربحت عقاراتك أثناء غيابك. تعال لتجمع أرباحك!","zh":"你不在时，你的房产赚了钱。快来收取吧！","ja":"留守中に物件が稼ぎました。回収に来よう！","ko":"자리를 비운 사이 부동산이 수익을 냈어요. 수령하러 오세요!","az":"Sən yox ikən mülklərin qazandı. Gəl yığ!","uk":"Поки тебе не було, нерухомість заробила. Приходь забирати!","fa":"در غیاب تو، املاکت درآمد کسب کردند. بیا و جمعش کن!","hi":"आपकी अनुपस्थिति में आपकी संपत्तियों ने कमाई की। आकर वसूलें!"],
        "notif_d3_title": ["tr":"🏙️ İmparatorluğun seni özledi","en":"🏙️ Your empire misses you","es":"🏙️ Tu imperio te echa de menos","fr":"🏙️ Ton empire te réclame","de":"🏙️ Dein Imperium vermisst dich","it":"🏙️ Il tuo impero ti aspetta","pt":"🏙️ Seu império sente sua falta","ru":"🏙️ Твоя империя скучает по тебе","ar":"🏙️ إمبراطوريتك تفتقدك","zh":"🏙️ 你的帝国想你了","ja":"🏙️ あなたの帝国が待っています","ko":"🏙️ 당신의 제국이 당신을 기다려요","az":"🏙️ İmperiyan səni darıxdı","uk":"🏙️ Твоя імперія сумує за тобою","fa":"🏙️ امپراتوری‌ات دلتنگ توست","hi":"🏙️ आपका साम्राज्य आपको याद कर रहा है"],
        "notif_d3_body":  ["tr":"Rakipler haritayı kapıyor. Bölgeni geri al.","en":"Rivals are buying up the map. Reclaim your turf.","es":"Los rivales están comprando el mapa. Recupera tu territorio.","fr":"Les rivaux raflent la carte. Reprends ton territoire.","de":"Rivalen kaufen die Karte auf. Hol dir dein Gebiet zurück.","it":"I rivali stanno comprando la mappa. Riprenditi il territorio.","pt":"Os rivais estão comprando o mapa. Retome seu território.","ru":"Соперники скупают карту. Верни свою территорию.","ar":"المنافسون يشترون الخريطة. استعد منطقتك.","zh":"对手正在抢占地图。夺回你的地盘。","ja":"ライバルが地図を買い占めています。縄張りを取り返そう。","ko":"라이벌들이 지도를 사들이고 있어요. 당신의 영역을 되찾으세요.","az":"Rəqiblər xəritəni tutur. Ərazini geri al.","uk":"Суперники скуповують карту. Поверни свою територію.","fa":"رقبا دارند نقشه را می‌خرند. قلمروت را پس بگیر.","hi":"प्रतिद्वंद्वी नक्शा खरीद रहे हैं। अपना इलाका वापस पाएं।"],
        "notif_d7_title": ["tr":"📉 Fiyatlar oynuyor","en":"📉 Prices are on the move","es":"📉 Los precios se mueven","fr":"📉 Les prix bougent","de":"📉 Die Preise bewegen sich","it":"📉 I prezzi si muovono","pt":"📉 Os preços estão mudando","ru":"📉 Цены пошли в движение","ar":"📉 الأسعار تتحرّك","zh":"📉 价格在波动","ja":"📉 相場が動いています","ko":"📉 시세가 움직이고 있어요","az":"📉 Qiymətlər dəyişir","uk":"📉 Ціни рухаються","fa":"📉 قیمت‌ها در حال تغییرند","hi":"📉 कीमतें हिल रही हैं"],
        "notif_d7_body":  ["tr":"Sen yokken piyasa değişti. Yeni fırsatlar seni bekliyor.","en":"The market shifted while you were gone. New deals await.","es":"El mercado cambió mientras no estabas. Te esperan nuevas oportunidades.","fr":"Le marché a changé en ton absence. De nouvelles affaires t'attendent.","de":"Der Markt hat sich verändert, während du weg warst. Neue Deals warten.","it":"Il mercato è cambiato mentre eri via. Nuovi affari ti aspettano.","pt":"O mercado mudou enquanto você esteve fora. Novas oportunidades esperam.","ru":"Пока тебя не было, рынок изменился. Тебя ждут новые сделки.","ar":"تغيّرت السوق أثناء غيابك. صفقات جديدة بانتظارك.","zh":"你离开时市场变了。新机会正等着你。","ja":"留守中に相場が動きました。新たなチャンスが待っています。","ko":"자리를 비운 사이 시장이 바뀌었어요. 새로운 기회가 기다립니다.","az":"Sən yox ikən bazar dəyişdi. Yeni fürsətlər səni gözləyir.","uk":"Поки тебе не було, ринок змінився. На тебе чекають нові угоди.","fa":"در غیاب تو بازار تغییر کرد. فرصت‌های تازه در انتظارند.","hi":"आपकी अनुपस्थिति में बाज़ार बदल गया। नए अवसर आपका इंतज़ार कर रहे हैं।"],

        // ── Referral (davet) ──
        "referral_title":     ["tr":"Arkadaşını davet et","en":"Invite friends","es":"Invita a tus amigos","fr":"Invite tes amis","de":"Freunde einladen","it":"Invita gli amici","pt":"Convide amigos","ru":"Пригласи друзей","ar":"ادعُ أصدقاءك","zh":"邀请好友","ja":"友達を招待","ko":"친구 초대","az":"Dostlarını dəvət et","uk":"Запроси друзів","fa":"دوستانت را دعوت کن","hi":"दोस्तों को आमंत्रित करें"],
        "referral_sub":       ["tr":"Davet et → sen +$3M, arkadaşın +$2M kazanır.","en":"Invite a friend → you get +$3M, they get +$2M.","es":"Invita a un amigo → tú ganas +3 M$, él gana +2 M$.","fr":"Invite un ami → tu gagnes +3 M$, il gagne +2 M$.","de":"Lade einen Freund ein → du bekommst +3 Mio. $, er bekommt +2 Mio. $.","it":"Invita un amico → tu ricevi +3 M$, lui riceve +2 M$.","pt":"Convide um amigo → você ganha +US$ 3 mi, ele ganha +US$ 2 mi.","ru":"Пригласи друга → ты получаешь +$3 млн, он +$2 млн.","ar":"ادعُ صديقًا ← تحصل على +3 ملايين دولار، ويحصل على +2 مليون دولار.","zh":"邀请好友 → 你得 +300 万美元，对方得 +200 万美元。","ja":"友達を招待 → あなたに +300万ドル、友達に +200万ドル。","ko":"친구 초대 → 당신은 +$3M, 친구는 +$2M 획득.","az":"Dost dəvət et → sən +$3M, dostun +$2M qazanır.","uk":"Запроси друга → ти отримуєш +$3 млн, він +$2 млн.","fa":"دوستی را دعوت کن ← تو +۳ میلیون دلار، او +۲ میلیون دلار می‌گیرد.","hi":"दोस्त को आमंत्रित करें → आपको +$3M, उन्हें +$2M मिलेगा।"],
        "referral_share":     ["tr":"Paylaş","en":"Share","es":"Compartir","fr":"Partager","de":"Teilen","it":"Condividi","pt":"Compartilhar","ru":"Поделиться","ar":"مشاركة","zh":"分享","ja":"シェア","ko":"공유","az":"Paylaş","uk":"Поділитися","fa":"اشتراک‌گذاری","hi":"साझा करें"],
        "referral_count":     ["tr":"%d davet · %@ kazandın","en":"%d invited · earned %@","es":"%d invitados · ganaste %@","fr":"%d invités · %@ gagnés","de":"%d eingeladen · %@ verdient","it":"%d invitati · guadagnati %@","pt":"%d convidados · ganhou %@","ru":"%d приглашено · заработано %@","ar":"%d مدعوّ · ربحت %@","zh":"已邀请 %d 人 · 赚得 %@","ja":"%d 人招待 · %@ 獲得","ko":"%d명 초대 · %@ 획득","az":"%d dəvət · %@ qazandın","uk":"%d запрошено · зароблено %@","fa":"%d دعوت · %@ کسب کردی","hi":"%d आमंत्रित · %@ कमाया"],
        "referral_enter_ph":  ["tr":"Davet kodu","en":"Invite code","es":"Código de invitación","fr":"Code d'invitation","de":"Einladungscode","it":"Codice invito","pt":"Código de convite","ru":"Код приглашения","ar":"رمز الدعوة","zh":"邀请码","ja":"招待コード","ko":"초대 코드","az":"Dəvət kodu","uk":"Код запрошення","fa":"کد دعوت","hi":"आमंत्रण कोड"],
        "referral_ok":        ["tr":"✓ %@ hesabına eklendi!","en":"✓ %@ added to your account!","es":"✓ ¡%@ añadidos a tu cuenta!","fr":"✓ %@ ajoutés à ton compte !","de":"✓ %@ deinem Konto gutgeschrieben!","it":"✓ %@ aggiunti al tuo conto!","pt":"✓ %@ adicionados à sua conta!","ru":"✓ %@ зачислено на счёт!","ar":"✓ تمت إضافة %@ إلى حسابك!","zh":"✓ %@ 已存入你的账户！","ja":"✓ %@ をアカウントに追加しました！","ko":"✓ %@이(가) 계정에 추가되었습니다!","az":"✓ %@ hesabına əlavə olundu!","uk":"✓ %@ додано до твого рахунку!","fa":"✓ %@ به حسابت اضافه شد!","hi":"✓ %@ आपके खाते में जोड़ा गया!"],
        "referral_err":       ["tr":"Geçersiz veya kullanılmış kod","en":"Invalid or already-used code","es":"Código no válido o ya usado","fr":"Code invalide ou déjà utilisé","de":"Ungültiger oder bereits benutzter Code","it":"Codice non valido o già usato","pt":"Código inválido ou já usado","ru":"Неверный или уже использованный код","ar":"رمز غير صالح أو مُستخدَم من قبل","zh":"无效或已使用的邀请码","ja":"無効または使用済みのコードです","ko":"유효하지 않거나 이미 사용된 코드","az":"Yanlış və ya artıq istifadə olunmuş kod","uk":"Недійсний або вже використаний код","fa":"کد نامعتبر یا قبلاً استفاده‌شده","hi":"अमान्य या पहले से इस्तेमाल किया गया कोड"],
        "referral_share_msg": ["tr":"Hooder'da gerçek binalardan emlak imparatorluğu kur! Davet kodum: %CODE% — apps.apple.com/app/id6776767786","en":"Build a property empire from real buildings on Hooder! My invite code: %CODE% — apps.apple.com/app/id6776767786","es":"¡Construye un imperio inmobiliario con edificios reales en Hooder! Mi código de invitación: %CODE% — apps.apple.com/app/id6776767786","fr":"Bâtis un empire immobilier à partir de vrais bâtiments sur Hooder ! Mon code d'invitation : %CODE% — apps.apple.com/app/id6776767786","de":"Baue auf Hooder ein Immobilienimperium aus echten Gebäuden! Mein Einladungscode: %CODE% — apps.apple.com/app/id6776767786","it":"Costruisci un impero immobiliare con edifici reali su Hooder! Il mio codice invito: %CODE% — apps.apple.com/app/id6776767786","pt":"Construa um império imobiliário com prédios reais no Hooder! Meu código de convite: %CODE% — apps.apple.com/app/id6776767786","ru":"Построй империю недвижимости из настоящих зданий в Hooder! Мой код приглашения: %CODE% — apps.apple.com/app/id6776767786","ar":"ابنِ إمبراطورية عقارية من مبانٍ حقيقية في Hooder! رمز دعوتي: %CODE% — apps.apple.com/app/id6776767786","zh":"在 Hooder 用真实建筑打造你的房地产帝国！我的邀请码：%CODE% — apps.apple.com/app/id6776767786","ja":"Hooderで実在の建物から不動産帝国を築こう！私の招待コード：%CODE% — apps.apple.com/app/id6776767786","ko":"Hooder에서 실제 건물로 부동산 제국을 세우세요! 제 초대 코드: %CODE% — apps.apple.com/app/id6776767786","az":"Hooder-də real binalardan əmlak imperiyası qur! Dəvət kodum: %CODE% — apps.apple.com/app/id6776767786","uk":"Збудуй імперію нерухомості зі справжніх будівель у Hooder! Мій код запрошення: %CODE% — apps.apple.com/app/id6776767786","fa":"در Hooder از ساختمان‌های واقعی یک امپراتوری املاک بساز! کد دعوت من: %CODE% — apps.apple.com/app/id6776767786","hi":"Hooder पर असली इमारतों से रियल एस्टेट साम्राज्य बनाएं! मेरा आमंत्रण कोड: %CODE% — apps.apple.com/app/id6776767786"],

        // ── Emlak Firması (klan) ──
        "tab_firm":            ["tr":"Firma","en":"Firm","es":"Firma","fr":"Agence","de":"Firma","it":"Agenzia","pt":"Firma","ru":"Фирма","ar":"شركة","zh":"公司","ja":"会社","ko":"회사","az":"Firma","uk":"Фірма","fa":"شرکت","hi":"फर्म"],
        "firm_members":        ["tr":"Üye","en":"Members","es":"Miembros","fr":"Membres","de":"Mitglieder","it":"Membri","pt":"Membros","ru":"Участники","ar":"الأعضاء","zh":"成员","ja":"メンバー","ko":"멤버","az":"Üzvlər","uk":"Учасники","fa":"اعضا","hi":"सदस्य"],
        "firm_treasury":       ["tr":"Kasa","en":"Treasury","es":"Tesorería","fr":"Trésorerie","de":"Kasse","it":"Cassa","pt":"Tesouro","ru":"Казна","ar":"الخزينة","zh":"金库","ja":"金庫","ko":"금고","az":"Kassa","uk":"Скарбниця","fa":"خزانه","hi":"कोष"],
        "firm_contribute":     ["tr":"Katkı","en":"Contribute","es":"Aportar","fr":"Contribuer","de":"Beitragen","it":"Contribuisci","pt":"Contribuir","ru":"Внести","ar":"مساهمة","zh":"贡献","ja":"寄付","ko":"기부","az":"Töhfə ver","uk":"Внести","fa":"مشارکت","hi":"योगदान"],
        "firm_contribute_hint":["tr":"Katkın ortak havuza gider; ihtiyacı olan üye çeker. Kimseye hedefli gönderim yok.","en":"Your contribution goes to the shared pool; members in need claim from it. No targeted transfers.","es":"Tu aporte va al fondo común; los miembros que lo necesitan lo retiran. No hay envíos dirigidos.","fr":"Ta contribution va au fonds commun; les membres dans le besoin y puisent. Aucun transfert ciblé.","de":"Dein Beitrag fließt in den gemeinsamen Topf; bedürftige Mitglieder heben davon ab. Keine gezielten Überweisungen.","it":"Il tuo contributo va al fondo comune; i membri in difficoltà attingono da lì. Nessun invio mirato.","pt":"Sua contribuição vai para o fundo comum; membros que precisam retiram dele. Sem envios direcionados.","ru":"Ваш вклад идёт в общий фонд; нуждающиеся участники берут из него. Адресных переводов нет.","ar":"مساهمتك تذهب إلى الصندوق المشترك؛ يسحب منها الأعضاء المحتاجون. لا تحويلات موجهة.","zh":"你的贡献进入共享资金池；有需要的成员从中领取。没有定向转账。","ja":"あなたの寄付は共有プールに入り、必要な会員が受け取ります。個別送金はありません。","ko":"기여금은 공동 풀로 들어가며 필요한 멤버가 가져갑니다. 지정 송금은 없습니다.","az":"Töhfən ortaq fonda gedir; ehtiyacı olan üzv oradan götürür. Hədəfli göndərmə yoxdur.","uk":"Ваш внесок іде до спільного фонду; учасники, які потребують, беруть із нього. Адресних переказів немає.","fa":"مشارکت شما به صندوق مشترک می‌رود؛ اعضای نیازمند از آن برداشت می‌کنند. انتقال هدفمند وجود ندارد.","hi":"आपका योगदान साझा कोष में जाता है; ज़रूरतमंद सदस्य उससे लेते हैं। कोई लक्षित स्थानांतरण नहीं।"],
        "firm_amount_ph":      ["tr":"Miktar","en":"Amount","es":"Cantidad","fr":"Montant","de":"Betrag","it":"Importo","pt":"Valor","ru":"Сумма","ar":"المبلغ","zh":"金额","ja":"金額","ko":"금액","az":"Məbləğ","uk":"Сума","fa":"مبلغ","hi":"राशि"],
        "firm_aid":            ["tr":"Günlük Destek Al","en":"Claim daily support","es":"Reclamar apoyo diario","fr":"Réclamer l'aide quotidienne","de":"Tägliche Unterstützung abholen","it":"Richiedi il supporto giornaliero","pt":"Resgatar apoio diário","ru":"Получить дневную поддержку","ar":"احصل على الدعم اليومي","zh":"领取每日支持","ja":"毎日の支援を受け取る","ko":"일일 지원 받기","az":"Günlük dəstək al","uk":"Отримати щоденну підтримку","fa":"دریافت حمایت روزانه","hi":"दैनिक सहायता लें"],
        "firm_aid_hint":       ["tr":"Günde bir kez kasadan net %@ (%%20 vergi kesilir).","en":"Once a day, net %@ from the treasury (20%% tax applies).","es":"Una vez al día, %@ neto de la tesorería (se aplica %%20 de impuesto).","fr":"Une fois par jour, %@ net de la trésorerie (%%20 de taxe s'applique).","de":"Einmal täglich netto %@ aus der Kasse (%%20 Steuer fällt an).","it":"Una volta al giorno, %@ netti dalla cassa (si applica il %%20 di tassa).","pt":"Uma vez por dia, %@ líquido do tesouro (aplica-se %%20 de imposto).","ru":"Раз в день чистыми %@ из казны (удерживается налог %%20).","ar":"مرة واحدة يوميا، صافي %@ من الخزينة (تطبق ضريبة %%20).","zh":"每天一次，从金库净得 %@（收取 %%20 税）。","ja":"1日1回、金庫から正味 %@（%%20 の税が適用）。","ko":"하루에 한 번, 금고에서 순 %@ (%%20 세금 적용).","az":"Gündə bir dəfə kassadan xalis %@ (%%20 vergi tutulur).","uk":"Раз на день чистими %@ зі скарбниці (стягується %%20 податку).","fa":"روزی یک بار، خالص %@ از خزانه (%%20 مالیات کسر می‌شود).","hi":"दिन में एक बार, कोष से शुद्ध %@ (%%20 कर लगता है)।"],
        "firm_received":       ["tr":"Aldığın","en":"Received","es":"Recibido","fr":"Reçu","de":"Erhalten","it":"Ricevuto","pt":"Recebido","ru":"Получено","ar":"المستلم","zh":"已领取","ja":"受取済み","ko":"받음","az":"Aldığın","uk":"Отримано","fa":"دریافت‌شده","hi":"प्राप्त"],
        "firm_you":            ["tr":"Sen","en":"You","es":"Tú","fr":"Toi","de":"Du","it":"Tu","pt":"Você","ru":"Вы","ar":"أنت","zh":"你","ja":"あなた","ko":"나","az":"Sən","uk":"Ви","fa":"شما","hi":"आप"],
        "firm_create":         ["tr":"Firma Kur","en":"Create firm","es":"Crear firma","fr":"Créer une agence","de":"Firma gründen","it":"Crea agenzia","pt":"Criar firma","ru":"Создать фирму","ar":"إنشاء شركة","zh":"创建公司","ja":"会社を設立","ko":"회사 만들기","az":"Firma yarat","uk":"Створити фірму","fa":"ایجاد شرکت","hi":"फर्म बनाएं"],
        "firm_create_hint":    ["tr":"Kendi emlak firmanı kur, üye topla, kasada dayanışın.","en":"Start your own real-estate firm, gather members, pool support.","es":"Crea tu propia firma inmobiliaria, reúne miembros y apóyense en la tesorería.","fr":"Crée ta propre agence immobilière, rassemble des membres, entraidez-vous via la trésorerie.","de":"Gründe deine eigene Immobilienfirma, sammle Mitglieder und unterstützt euch über die Kasse.","it":"Crea la tua agenzia immobiliare, raduna membri e sostenetevi tramite la cassa.","pt":"Crie sua própria firma imobiliária, reúna membros e apoiem-se no tesouro.","ru":"Создайте свою риелторскую фирму, соберите участников и поддерживайте друг друга через казну.","ar":"أنشئ شركتك العقارية، اجمع الأعضاء، وتضامنوا عبر الخزينة.","zh":"创办你自己的房地产公司，招募成员，用金库互相扶持。","ja":"自分の不動産会社を設立し、仲間を集め、金庫で助け合おう。","ko":"자신의 부동산 회사를 만들고 멤버를 모아 금고로 서로 도우세요.","az":"Öz əmlak firmanı yarat, üzv topla, kassa ilə dayanışın.","uk":"Створіть власну ріелторську фірму, зберіть учасників і підтримуйте одне одного через скарбницю.","fa":"شرکت املاک خود را بساز، عضو جمع کن و از طریق خزانه با هم همراه شوید.","hi":"अपनी खुद की रियल-एस्टेट फर्म बनाएं, सदस्य जुटाएं और कोष से एक-दूसरे का साथ दें।"],
        "firm_name_ph":        ["tr":"Firma adı","en":"Firm name","es":"Nombre de la firma","fr":"Nom de l'agence","de":"Firmenname","it":"Nome dell'agenzia","pt":"Nome da firma","ru":"Название фирмы","ar":"اسم الشركة","zh":"公司名称","ja":"会社名","ko":"회사 이름","az":"Firma adı","uk":"Назва фірми","fa":"نام شرکت","hi":"फर्म का नाम"],
        "firm_create_cost":    ["tr":"Maliyet","en":"Cost","es":"Coste","fr":"Coût","de":"Kosten","it":"Costo","pt":"Custo","ru":"Стоимость","ar":"التكلفة","zh":"费用","ja":"費用","ko":"비용","az":"Xərc","uk":"Вартість","fa":"هزینه","hi":"लागत"],
        "firm_join_title":     ["tr":"Bir firmaya katıl","en":"Join a firm","es":"Únete a una firma","fr":"Rejoindre une agence","de":"Einer Firma beitreten","it":"Unisciti a un'agenzia","pt":"Entrar numa firma","ru":"Присоединиться к фирме","ar":"انضم إلى شركة","zh":"加入公司","ja":"会社に参加","ko":"회사에 가입","az":"Bir firmaya qoşul","uk":"Приєднатися до фірми","fa":"عضویت در یک شرکت","hi":"किसी फर्म में शामिल हों"],
        "firm_join":           ["tr":"Katıl","en":"Join","es":"Unirse","fr":"Rejoindre","de":"Beitreten","it":"Unisciti","pt":"Entrar","ru":"Вступить","ar":"انضمام","zh":"加入","ja":"参加","ko":"가입","az":"Qoşul","uk":"Приєднатися","fa":"عضویت","hi":"शामिल हों"],
        "firm_board":          ["tr":"Firma Sıralaması","en":"Firm rankings","es":"Clasificación de firmas","fr":"Classement des agences","de":"Firmen-Rangliste","it":"Classifica agenzie","pt":"Ranking de firmas","ru":"Рейтинг фирм","ar":"ترتيب الشركات","zh":"公司排行","ja":"会社ランキング","ko":"회사 순위","az":"Firma sıralaması","uk":"Рейтинг фірм","fa":"رتبه‌بندی شرکت‌ها","hi":"फर्म रैंकिंग"],
        "firm_msg_created":    ["tr":"🏢 Firman kuruldu!","en":"🏢 Your firm is live!","es":"🏢 ¡Tu firma está activa!","fr":"🏢 Ton agence est active !","de":"🏢 Deine Firma ist online!","it":"🏢 La tua agenzia è attiva!","pt":"🏢 Sua firma está ativa!","ru":"🏢 Ваша фирма создана!","ar":"🏢 شركتك جاهزة!","zh":"🏢 你的公司已成立！","ja":"🏢 会社が設立されました！","ko":"🏢 회사가 만들어졌어요!","az":"🏢 Firman yaradıldı!","uk":"🏢 Вашу фірму створено!","fa":"🏢 شرکت شما فعال شد!","hi":"🏢 आपकी फर्म शुरू हो गई!"],
        "firm_msg_joined":     ["tr":"Firmaya katıldın.","en":"You joined the firm.","es":"Te uniste a la firma.","fr":"Tu as rejoint l'agence.","de":"Du bist der Firma beigetreten.","it":"Ti sei unito all'agenzia.","pt":"Você entrou na firma.","ru":"Вы вступили в фирму.","ar":"لقد انضممت إلى الشركة.","zh":"你已加入公司。","ja":"会社に参加しました。","ko":"회사에 가입했습니다.","az":"Firmaya qoşuldun.","uk":"Ви приєдналися до фірми.","fa":"به شرکت پیوستید.","hi":"आप फर्म में शामिल हो गए।"],
        "firm_msg_contributed":["tr":"Kasaya katkı yapıldı.","en":"Contributed to the treasury.","es":"Aporte hecho a la tesorería.","fr":"Contribution versée à la trésorerie.","de":"Beitrag zur Kasse geleistet.","it":"Contributo versato in cassa.","pt":"Contribuição feita ao tesouro.","ru":"Взнос в казну сделан.","ar":"تمت المساهمة في الخزينة.","zh":"已向金库贡献。","ja":"金庫に寄付しました。","ko":"금고에 기여했습니다.","az":"Kassaya töhfə verildi.","uk":"Внесок до скарбниці зроблено.","fa":"مشارکت به خزانه انجام شد.","hi":"कोष में योगदान किया गया।"],
        "firm_msg_aid":        ["tr":"✓ %@ destek alındı.","en":"✓ Received %@ support.","es":"✓ Recibido %@ de apoyo.","fr":"✓ %@ d'aide reçue.","de":"✓ %@ Unterstützung erhalten.","it":"✓ Ricevuto %@ di supporto.","pt":"✓ Recebido %@ de apoio.","ru":"✓ Получено %@ поддержки.","ar":"✓ تم استلام دعم %@.","zh":"✓ 已领取 %@ 支持。","ja":"✓ %@ の支援を受け取りました。","ko":"✓ %@ 지원을 받았습니다.","az":"✓ %@ dəstək alındı.","uk":"✓ Отримано %@ підтримки.","fa":"✓ حمایت %@ دریافت شد.","hi":"✓ %@ सहायता प्राप्त हुई।"],
        "firm_msg_left":       ["tr":"Firmadan ayrıldın.","en":"You left the firm.","es":"Saliste de la firma.","fr":"Tu as quitté l'agence.","de":"Du hast die Firma verlassen.","it":"Hai lasciato l'agenzia.","pt":"Você saiu da firma.","ru":"Вы покинули фирму.","ar":"لقد غادرت الشركة.","zh":"你已离开公司。","ja":"会社を退会しました。","ko":"회사에서 나갔습니다.","az":"Firmadan ayrıldın.","uk":"Ви покинули фірму.","fa":"از شرکت خارج شدید.","hi":"आप फर्म से बाहर हो गए।"],
        "firm_msg_fail":       ["tr":"İşlem başarısız.","en":"Action failed.","es":"La acción falló.","fr":"L'action a échoué.","de":"Aktion fehlgeschlagen.","it":"Azione non riuscita.","pt":"A ação falhou.","ru":"Действие не удалось.","ar":"فشلت العملية.","zh":"操作失败。","ja":"操作に失敗しました。","ko":"작업에 실패했습니다.","az":"Əməliyyat uğursuz oldu.","uk":"Дію не виконано.","fa":"عملیات ناموفق بود.","hi":"कार्रवाई विफल रही।"],

        // ── Merkez Bankası (ülke / ekonomik savaş) ──
        "cb_title":            ["tr":"Merkez Bankası","en":"Central Bank","es":"Banco Central","fr":"Banque centrale","de":"Zentralbank","it":"Banca centrale","pt":"Banco Central","ru":"Центральный банк","ar":"البنك المركزي","zh":"中央银行","ja":"中央銀行","ko":"중앙은행","az":"Mərkəzi Bank","uk":"Центральний банк","fa":"بانک مرکزی","hi":"केंद्रीय बैंक"],
        "cb_players":          ["tr":"oyuncu","en":"players","es":"jugadores","fr":"joueurs","de":"Spieler","it":"giocatori","pt":"jogadores","ru":"игроки","ar":"لاعبون","zh":"玩家","ja":"プレイヤー","ko":"플레이어","az":"oyunçular","uk":"гравці","fa":"بازیکنان","hi":"खिलाड़ी"],
        "cb_power":            ["tr":"Ülke Gücü","en":"Power","es":"Poder","fr":"Puissance","de":"Stärke","it":"Potenza","pt":"Poder","ru":"Мощь","ar":"القوة","zh":"国力","ja":"国力","ko":"국력","az":"Güc","uk":"Сила","fa":"قدرت","hi":"शक्ति"],
        "cb_treasury":         ["tr":"Hazine","en":"Treasury","es":"Tesoro","fr":"Trésor","de":"Staatskasse","it":"Tesoro","pt":"Tesouro","ru":"Казна","ar":"الخزانة","zh":"国库","ja":"国庫","ko":"국고","az":"Xəzinə","uk":"Скарбниця","fa":"خزانه","hi":"खजाना"],
        "cb_base_currency":    ["tr":"Rezerv para birimi","en":"Reserve currency","es":"Moneda de reserva","fr":"Monnaie de réserve","de":"Reservewährung","it":"Valuta di riserva","pt":"Moeda de reserva","ru":"Резервная валюта","ar":"العملة الاحتياطية","zh":"储备货币","ja":"準備通貨","ko":"준비 통화","az":"Ehtiyat valyutası","uk":"Резервна валюта","fa":"ارز ذخیره","hi":"आरक्षित मुद्रा"],
        "cb_contribute":       ["tr":"Hazineye Katkı","en":"Contribute","es":"Contribuir","fr":"Contribuer","de":"Beitragen","it":"Contribuisci","pt":"Contribuir","ru":"Внести вклад","ar":"ساهم","zh":"贡献","ja":"貢献する","ko":"기여하기","az":"Töhfə ver","uk":"Зробити внесок","fa":"مشارکت","hi":"योगदान करें"],
        "cb_contribute_hint":  ["tr":"Katkın ulusal hazineye gider → ülken güçlenir, para birimin değer kazanır.","en":"Your contribution builds the national treasury — your country and its currency grow stronger.","es":"Tu contribución alimenta el tesoro nacional: tu país y su moneda se fortalecen.","fr":"Ta contribution alimente le trésor national — ton pays et sa monnaie se renforcent.","de":"Dein Beitrag stärkt die Staatskasse — dein Land und seine Währung werden stärker.","it":"Il tuo contributo alimenta il tesoro nazionale: il tuo Paese e la sua valuta si rafforzano.","pt":"Sua contribuição alimenta o tesouro nacional — seu país e sua moeda ficam mais fortes.","ru":"Ваш вклад пополняет национальную казну — страна и её валюта крепнут.","ar":"مساهمتك تعزز الخزانة الوطنية — تقوى دولتك وعملتها.","zh":"你的贡献充实国库——国家和货币都会变得更强大。","ja":"あなたの貢献が国庫を支え、国と通貨がより強くなります。","ko":"당신의 기여가 국고를 채워 국가와 통화를 강하게 만듭니다.","az":"Töhfən milli xəzinəni gücləndirir — ölkən və valyutası daha da güclənir.","uk":"Твій внесок наповнює національну скарбницю — країна та її валюта міцніють.","fa":"مشارکت شما خزانه ملی را تقویت می‌کند — کشور و ارزش پول آن قوی‌تر می‌شود.","hi":"आपका योगदान राष्ट्रीय खजाने को मजबूत करता है — आपका देश और उसकी मुद्रा और शक्तिशाली बनते हैं।"],
        "cb_choose":           ["tr":"Ülkeni seç","en":"Choose your country","es":"Elige tu país","fr":"Choisis ton pays","de":"Wähle dein Land","it":"Scegli il tuo Paese","pt":"Escolha seu país","ru":"Выберите страну","ar":"اختر دولتك","zh":"选择你的国家","ja":"国を選ぶ","ko":"국가 선택","az":"Ölkəni seç","uk":"Обери свою країну","fa":"کشور خود را انتخاب کنید","hi":"अपना देश चुनें"],
        "cb_choose_hint":      ["tr":"Bir ülke seç ve merkez bankasına katkı yaparak onu ekonomik savaşta zirveye taşı.","en":"Pick a country and strengthen its central bank to climb the economic war.","es":"Elige un país y refuerza su banco central para llevarlo a lo más alto de la guerra económica.","fr":"Choisis un pays et renforce sa banque centrale pour le hisser au sommet de la guerre économique.","de":"Wähle ein Land und stärke seine Zentralbank, um es im Wirtschaftskrieg an die Spitze zu bringen.","it":"Scegli un Paese e rafforza la sua banca centrale per portarlo in cima alla guerra economica.","pt":"Escolha um país e reforce seu banco central para levá-lo ao topo da guerra econômica.","ru":"Выберите страну и укрепляйте её центральный банк, чтобы вывести её на вершину экономической войны.","ar":"اختر دولة وعزز بنكها المركزي لترتقي بها إلى قمة الحرب الاقتصادية.","zh":"选择一个国家，强化其中央银行，助它登上经济战争的顶峰。","ja":"国を選び、その中央銀行を強化して経済戦争の頂点へ導こう。","ko":"국가를 선택하고 중앙은행을 강화해 경제 전쟁의 정상에 올려보세요.","az":"Bir ölkə seç və mərkəzi bankını gücləndirərək onu iqtisadi müharibədə zirvəyə daşı.","uk":"Обери країну та зміцнюй її центральний банк, щоб вивести її на вершину економічної війни.","fa":"کشوری را انتخاب کنید و با تقویت بانک مرکزی آن، آن را به قله جنگ اقتصادی برسانید.","hi":"एक देश चुनें और उसके केंद्रीय बैंक को मजबूत करके उसे आर्थिक युद्ध में शीर्ष पर पहुंचाएं।"],
        "cb_choose_btn":       ["tr":"Seç","en":"Choose","es":"Elegir","fr":"Choisir","de":"Wählen","it":"Scegli","pt":"Escolher","ru":"Выбрать","ar":"اختر","zh":"选择","ja":"選ぶ","ko":"선택","az":"Seç","uk":"Обрати","fa":"انتخاب","hi":"चुनें"],
        "cb_war":              ["tr":"Ekonomik Savaş","en":"Economic war","es":"Guerra económica","fr":"Guerre économique","de":"Wirtschaftskrieg","it":"Guerra economica","pt":"Guerra econômica","ru":"Экономическая война","ar":"الحرب الاقتصادية","zh":"经济战争","ja":"経済戦争","ko":"경제 전쟁","az":"İqtisadi müharibə","uk":"Економічна війна","fa":"جنگ اقتصادی","hi":"आर्थिक युद्ध"],
        "cb_msg_joined":       ["tr":"🏛️ Ülken seçildi!","en":"🏛️ Country set!","es":"🏛️ ¡País seleccionado!","fr":"🏛️ Pays sélectionné !","de":"🏛️ Land ausgewählt!","it":"🏛️ Paese selezionato!","pt":"🏛️ País selecionado!","ru":"🏛️ Страна выбрана!","ar":"🏛️ تم اختيار دولتك!","zh":"🏛️ 国家已选定！","ja":"🏛️ 国が決定しました！","ko":"🏛️ 국가가 설정되었습니다!","az":"🏛️ Ölkən seçildi!","uk":"🏛️ Країну обрано!","fa":"🏛️ کشور انتخاب شد!","hi":"🏛️ देश चुना गया!"],
        "cb_msg_contributed":  ["tr":"Ulusal hazineye katkı yapıldı.","en":"Contributed to the national treasury.","es":"Contribuiste al tesoro nacional.","fr":"Contribution versée au trésor national.","de":"Beitrag zur Staatskasse geleistet.","it":"Contributo versato al tesoro nazionale.","pt":"Contribuição feita ao tesouro nacional.","ru":"Вклад в национальную казну внесён.","ar":"تمت المساهمة في الخزانة الوطنية.","zh":"已为国库作出贡献。","ja":"国庫に貢献しました。","ko":"국고에 기여했습니다.","az":"Milli xəzinəyə töhfə verildi.","uk":"Внесок у національну скарбницю зроблено.","fa":"به خزانه ملی مشارکت انجام شد.","hi":"राष्ट्रीय खजाने में योगदान किया गया।"],
    ]
}

// Global kısayol — View body içinde çağrılırsa dil değişimine tepki verir.
@MainActor func t(_ key: String) -> String { L10n.shared.t(key) }
